apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: kcp-admin-frontproxy-internal
  namespace: kcp-comer
spec:
  username: kcp-admin
  groups:
    - system:kcp:admin
  validity: 8766h
  secretRef:
    name: kcp-admin-frontproxy-internal
  target:
    frontProxyRef:
      name: frontproxy-internal
