---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: apiresourceimports.apiresource.kcp.dev
spec:
  group: apiresource.kcp.dev
  names:
    categories:
    - kcp
    kind: APIResourceImport
    listKind: APIResourceImportList
    plural: apiresourceimports
    singular: apiresourceimport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.location
      name: Location
      priority: 1
      type: string
    - jsonPath: .spec.schemaUpdateStrategy
      name: Schema update strategy
      priority: 2
      type: string
    - jsonPath: .metadata.annotations.apiresource\.kcp\.dev/apiVersion
      name: API Version
      priority: 3
      type: string
    - jsonPath: .spec.plural
      name: API Resource
      priority: 4
      type: string
    - jsonPath: .status.conditions[?(@.type=="Compatible")].status
      name: Compatible
      priority: 5
      type: string
    - jsonPath: .status.conditions[?(@.type=="Available")].status
      name: Available
      priority: 6
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: APIResourceImport describes an API resource imported from external
          clusters (either physical or logical) for a given GVR.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: APIResourceImportSpec holds the desired state of the APIResourceImport
              (from the client).
            properties:
              categories:
                description: categories is a list of grouped resources this custom
                  resource belongs to (e.g. 'all'). This is published in API discovery
                  documents, and used by clients to support invocations like `kubectl
                  get all`.
                items:
                  type: string
                type: array
              columnDefinitions:
                items:
                  properties:
                    description:
                      description: description is a human readable description of
                        this column.
                      type: string
                    format:
                      description: format is an optional OpenAPI type modifier for
                        this column. A format modifies the type and imposes additional
                        rules, like date or time formatting for a string. The 'name'
                        format is applied to the primary identifier column which has
                        type 'string' to assist in clients identifying column is the
                        resource name. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
                        for more.
                      type: string
                    jsonPath:
                      type: string
                    name:
                      description: name is a human readable name for the column.
                      type: string
                    priority:
                      description: priority is an integer defining the relative importance
                        of this column compared to others. Lower numbers are considered
                        higher priority. Columns that may be omitted in limited space
                        scenarios should be given a higher priority.
                      format: int32
                      type: integer
                    type:
                      description: type is an OpenAPI type definition for this column,
                        such as number, integer, string, or array. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
                        for more.
                      type: string
                  required:
                  - description
                  - format
                  - jsonPath
                  - name
                  - priority
                  - type
                  type: object
                type: array
              groupVersion:
                properties:
                  group:
                    type: string
                  version:
                    type: string
                required:
                - version
                type: object
              kind:
                description: kind is the serialized kind of the resource. It is normally
                  CamelCase and singular. Custom resource instances will use this
                  value as the `kind` attribute in API calls.
                type: string
              listKind:
                description: listKind is the serialized kind of the list for this
                  resource. Defaults to "`kind`List".
                type: string
              location:
                description: Locaton the API resource is imported from This field
                  is required
                type: string
              openAPIV3Schema:
                type: object
                x-kubernetes-map-type: atomic
                x-kubernetes-preserve-unknown-fields: true
              plural:
                description: plural is the plural name of the resource to serve. The
                  custom resources are served under `/apis/<group>/<version>/.../<plural>`.
                  Must match the name of the CustomResourceDefinition (in the form
                  `<names.plural>.<group>`). Must be all lowercase.
                type: string
              schemaUpdateStrategy:
                description: SchemaUpdateStrategy defines the schema update strategy
                  for this API Resource import. Default value is UpdateUnpublished
                type: string
              scope:
                description: ResourceScope is an enum defining the different scopes
                  available to a custom resource
                type: string
              shortNames:
                description: shortNames are short names for the resource, exposed
                  in API discovery documents, and used by clients to support invocations
                  like `kubectl get <shortname>`. It must be all lowercase.
                items:
                  type: string
                type: array
              singular:
                description: singular is the singular name of the resource. It must
                  be all lowercase. Defaults to lowercased `kind`.
                type: string
              subResources:
                items:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
            required:
            - groupVersion
            - kind
            - location
            - openAPIV3Schema
            - plural
            - scope
            type: object
          status:
            description: APIResourceImportStatus communicates the observed state of
              the APIResourceImport (from the controller).
            properties:
              conditions:
                items:
                  description: APIResourceImportCondition contains details for the
                    current condition of this negotiated api resource.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition. Types include
                        Compatible.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
