apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.io
spec:
  latestResourceSchemas:
  - v221219-c92ed8152.clusterworkspaces.tenancy.kcp.io
  - v230313-2197e455a.workspacetypes.tenancy.kcp.io
  - v231119-434294a3b.workspaces.tenancy.kcp.io
  maximalPermissionPolicy:
    local: {}
status: {}
