apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v220915-b4cf5d4e.clusterworkspaces.tenancy.kcp.dev
  - v220915-b4cf5d4e.workspaces.tenancy.kcp.dev
  - v220923-596b9074.clusterworkspacetypes.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
