apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: tenancy.kcp.io
spec:
  maximalPermissionPolicy:
    local: {}
  resources:
  - group: tenancy.kcp.io
    name: workspaceauthenticationconfigurations
    schema: v250827-717cfea84.workspaceauthenticationconfigurations.tenancy.kcp.io
    storage:
      crd: {}
  - group: tenancy.kcp.io
    name: workspaces
    schema: v251015-1d163d0e5.workspaces.tenancy.kcp.io
    storage:
      crd: {}
  - group: tenancy.kcp.io
    name: workspacetypes
    schema: v251204-7c13b4e0a.workspacetypes.tenancy.kcp.io
    storage:
      crd: {}
status: {}
