apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: cache.kcp.io
spec:
  resources:
  - group: cache.kcp.io
    name: cachedresourceendpointslices
    schema: v251120-d8e87a979.cachedresourceendpointslices.cache.kcp.io
    storage:
      crd: {}
  - group: cache.kcp.io
    name: cachedresources
    schema: v250920-de0c8484d.cachedresources.cache.kcp.io
    storage:
      crd: {}
status: {}
