apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: topology.kcp.io
spec:
  resources:
  - group: topology.kcp.io
    name: partitions
    schema: v240903-d6797056a.partitions.topology.kcp.io
    storage:
      crd: {}
  - group: topology.kcp.io
    name: partitionsets
    schema: v240903-d6797056a.partitionsets.topology.kcp.io
    storage:
      crd: {}
status: {}
