apiVersion: apis.kcp.dev/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v221204-5bf97087f.synctargets.workload.kcp.dev
spec:
  group: workload.kcp.dev
  names:
    categories:
    - kcp
    kind: SyncTarget
    listKind: SyncTargetList
    plural: synctargets
    singular: synctarget
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Location
      priority: 1
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      priority: 2
      type: string
    - jsonPath: .status.syncedResources
      name: Synced API resources
      priority: 3
      type: string
    - jsonPath: .metadata.labels['internal\.workload\.kcp\.dev/key']
      name: Key
      priority: 4
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      description: SyncTarget describes a member cluster capable of running workloads.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          properties:
            name:
              maxLength: 234
              minLength: 1
              type: string
          type: object
        spec:
          description: Spec holds the desired state.
          properties:
            cells:
              additionalProperties:
                type: string
              description: Cells is a set of labels to identify the cells the SyncTarget
                belongs to. SyncTargets with the same cells run as they are in the
                same physical cluster. Each key/value pair in the cells should be
                added and updated by service providers (i.e. a network provider updates
                one key/value, while the storage provider updates another.)
              type: object
            evictAfter:
              description: EvictAfter controls cluster schedulability of new and existing
                workloads. After the EvictAfter time, any workload scheduled to the
                cluster will be unassigned from the cluster. By default, workloads
                scheduled to the cluster are not evicted.
              format: date-time
              type: string
            supportedAPIExports:
              default:
              - workspace:
                  exportName: kubernetes
              description: SupportedAPIExports defines a set of APIExports supposed
                to be supported by this SyncTarget. The SyncTarget will be selected
                to deploy the workload only when the resource schema on the SyncTarget
                is compatible with the resource schema included in the exports. If
                it is not set, the kubernetes export in the same workspace will be
                used by default.
              items:
                description: ExportReference describes a reference to an APIExport.
                  Exactly one of the fields must be set.
                properties:
                  workspace:
                    description: workspace is a reference to an APIExport in the same
                      organization. The creator of the APIBinding needs to have access
                      to the APIExport with the verb `bind` in order to bind to it.
                    properties:
                      exportName:
                        description: Name of the APIExport that describes the API.
                        type: string
                      path:
                        description: path is an absolute reference to a workspace,
                          e.g. root:org:ws. If it is unset, the path of the APIBinding
                          is used.
                        pattern: ^root(:[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                        type: string
                    required:
                    - exportName
                    type: object
                type: object
              type: array
            unschedulable:
              default: false
              description: Unschedulable controls cluster schedulability of new workloads.
                By default, cluster is schedulable.
              type: boolean
          type: object
        status:
          description: Status communicates the observed state.
          properties:
            allocatable:
              additionalProperties:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              description: Allocatable represents the resources that are available
                for scheduling.
              type: object
            capacity:
              additionalProperties:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              description: Capacity represents the total resources of the cluster.
              type: object
            conditions:
              description: Current processing state of the SyncTarget.
              items:
                description: Condition defines an observation of a object operational
                  state.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another. This should be when the underlying condition changed.
                      If that is not known, then using the time when the API field
                      changed is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition. This field may be empty.
                    type: string
                  reason:
                    description: The reason for the condition's last transition in
                      CamelCase. The specific API may choose whether or not this field
                      is considered a guaranteed API. This field may not be empty.
                    type: string
                  severity:
                    description: Severity provides an explicit classification of Reason
                      code, so the users or machines can immediately understand the
                      current situation and act accordingly. The Severity field MUST
                      be set only when Status=False.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources
                      like Available, but because arbitrary conditions can be useful
                      (see .node.status.conditions), the ability to deconflict is
                      important.
                    type: string
                required:
                - lastTransitionTime
                - status
                - type
                type: object
              type: array
            lastSyncerHeartbeatTime:
              description: A timestamp indicating when the syncer last reported status.
              format: date-time
              type: string
            syncedResources:
              description: SyncedResources represents the resources that the syncer
                of the SyncTarget can sync. It MUST be updated by kcp server.
              items:
                properties:
                  group:
                    description: group is the name of an API group. For core groups
                      this is the empty string '""'.
                    pattern: ^(|[a-z0-9]([-a-z0-9]*[a-z0-9](\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)?)$
                    type: string
                  identityHash:
                    description: identityHash is the identity for a given APIExport
                      that the APIResourceSchema belongs to. The hash can be found
                      on APIExport and APIResourceSchema's status. It will be empty
                      for core types.
                    type: string
                  resource:
                    description: 'resource is the name of the resource. Note: it is
                      worth noting that you can not ask for permissions for resource
                      provided by a CRD not provided by an api export.'
                    pattern: ^[a-z][-a-z0-9]*[a-z0-9]$
                    type: string
                  state:
                    default: Pending
                    description: state indicate whether the resources schema is compatible
                      to the SyncTarget. It must be updated by syncer after checking
                      the API compatibility on SyncTarget.
                    enum:
                    - Pending
                    - Accepted
                    - Incompatible
                    type: string
                  versions:
                    description: versions are the resource versions the syncer can
                      choose to sync depending on availability on the downstream cluster.
                      Conversion to the storage version, if necessary, will be done
                      on the kcp side. The versions are ordered by precedence and
                      the first version compatible is preferred by syncer.
                    items:
                      type: string
                    minItems: 1
                    type: array
                required:
                - resource
                - versions
                type: object
              type: array
            virtualWorkspaces:
              description: VirtualWorkspaces contains all syncer virtual workspace
                URLs.
              items:
                properties:
                  url:
                    description: URL is the URL of the syncer virtual workspace.
                    minLength: 1
                    type: string
                required:
                - url
                type: object
              type: array
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
