{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kcp-tmc.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcp-tmc.labels" . | nindent 4 }}
    component: kcp-server
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}