apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: frontproxy
spec:
  username: kcp-admin
  groups:
    - system:masters
    - system:kcp:admin
  validity: 8766h
  secretRef:
    name: kcp-frontproxy-kubeconfig
  target:
    frontProxyRef:
      name: frontproxy
---
apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: root
spec:
  username: kcp-admin
  groups:
    - system:masters
  validity: 8766h
  secretRef:
    name: kcp-root-kubeconfig
  target:
    rootShardRef:
      name: root
---
apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: theseus
spec:
  username: kcp-admin
  groups:
    - system:masters
  validity: 8766h
  secretRef:
    name: kcp-theseus-kubeconfig
  target:
    shardRef:
      name: theseus
