apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: kcp-admin-frontproxy
  namespace: kcp-vespucci
spec:
  username: kcp-admin
  groups:
    - system:kcp:admin
  validity: 8766h # 1 year
  secretRef:
    name: kcp-admin-frontproxy
  target:
    frontProxyRef:
      name: frontproxy