apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: home
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: Universal
    path: root
  limitAllowedParents:
    types:
    - name: Homebucket
      path: root
