apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:home-clusterworkspace-create
rules:
- apiGroups: ["tenancy.kcp.dev"]
  resources: ["workspaces"]
  resourceNames: ["~"]
  verbs: ["get"]
