apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:universal-workspacetype-use
rules:
- apiGroups: ["tenancy.kcp.dev"]
  resources:
  - "workspacetypes"
  resourceNames:
  - "universal"
  - "organization"
  - "team"
  verbs: ["use"]
