apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: universal
spec:
  initializer: true
  additionalWorkspaceLabels:
    workloads.kcp.dev/schedulable: "true"
  defaultChildWorkspaceType:
    name: Universal
    path: root
  allowAnyChildWorkspaceTypes: true
  allowAnyParentWorkspaceTypes: true
