name: Build and Publish KCP Image

permissions:
  packages: write

on:
  push:
    branches:
      - main
      - 'release-*'
    tags:
    - 'v*'
  pull_request:
    branches:
      - main
      - 'release-*'
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/workflows/docs-gen-and-push.yaml"
      - ".goreleaser.yaml"

jobs:
  build:
    if: github.repository_owner == 'kcp-dev'
    name: Build KCP Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: v1.19

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/kcp
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build binaries for images
        uses: docker/build-push-action@v4
        with:
          context: .
          target: builder
          load: true
          tags: kcp-build:latest
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          cache-from: type=gha,scope=${{ github.ref_name }}-buildx
          cache-to: type=gha,scope=${{ github.ref_name }}-buildx,mode=max

      - name: Build and push KCP image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: images/Dockerfile.kcp
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          cache-from: type=gha,scope=${{ github.ref_name }}-buildx
          cache-to: type=gha,scope=${{ github.ref_name }}-buildx,mode=max

      - name: Build and push kcp-front-proxy image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: images/Dockerfile.kcp-front-proxy
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          cache-from: type=gha,scope=${{ github.ref_name }}-buildx
          cache-to: type=gha,scope=${{ github.ref_name }}-buildx,mode=max

      - name: Build and push cache-server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: images/Dockerfile.cache-server
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          cache-from: type=gha,scope=${{ github.ref_name }}-buildx
          cache-to: type=gha,scope=${{ github.ref_name }}-buildx,mode=max

      - name: Build and push syncer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: images/Dockerfile.syncer
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          cache-from: type=gha,scope=${{ github.ref_name }}-buildx
          cache-to: type=gha,scope=${{ github.ref_name }}-buildx,mode=max
