name: Build and Publish KCP Image

permissions:
  packages: write

on:
  push:
    branches:
      - main
      - 'release-*'
    tags:
    - 'v*'

jobs:
  build:
    if: github.repository_owner == 'kcp-dev'
    name: Build KCP Image
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: v1.17

      - name: Get the short sha
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -b -7)"

      # Build and push a KCP image, tagged with latest and the commit SHA.
      - name: Build KCP Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kcp
          tags: latest ${{ steps.vars.outputs.sha_short }} ${{ github.ref_name }}
          containerfiles: |
            ./Dockerfile

      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} ${{ github.ref_name }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  deploy:
    if: "github.repository_owner == 'kcp-dev' && github.ref_name == 'main'"
    name: Deploy KCP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out shared-resources (gitops repo)
        uses: actions/checkout@v3
        with:
          repository: kcp-dev/shared-resources
          token: ${{ secrets.KCP_BOT_TOKEN }}

      - name: Update sha and commit
        run: |-
          sed -i -e 's/tag: [0-9a-f]\{7\}/tag: ${{ needs.build.outputs.sha_short }}/' manifest/unstable-values.yaml
          git add manifest/unstable-values.yaml
          git commit --author="KCP Bot <klape+kcp-bot@redhat.com>" -m "Automatic update of test environment to ${{ needs.build.outputs.sha_short }}"
          git push origin main
