name: Build and Publish KCP Image

permissions:
  packages: write

on:
  push:
    branches:
      - main
      - 'release-*'
    tags:
    - 'v*'

jobs:
  build:
    if: github.repository_owner == 'kcp-dev'
    name: Build KCP Image
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Get the short sha
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -b -7)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Build and push a KCP image, tagged with latest and the commit SHA.
      - name: Build KCP Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kcp
          tags: latest ${{ steps.vars.outputs.sha_short }} ${{ github.ref_name }}
          archs: amd64, ppc64le, arm64
          containerfiles: |
            ./Dockerfile

      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} ${{ github.ref_name }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
