name: Build and Publish KCP Image

permissions:
  packages: write

on:
  push:
    branches:
      - main
      - 'release-*'
    tags:
    - 'v*'

jobs:
  build:
    if: github.repository_owner == 'kcp-dev'
    name: Build KCP Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17

      - name: Get the short sha
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -b -7)"

      # Build and push a KCP image, tagged with latest and the commit SHA.
      - name: Build KCP Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kcp
          tags: latest ${{ steps.vars.outputs.sha_short }} ${{ github.ref_name }}
          containerfiles: |
            ./Dockerfile

      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }} ${{ github.ref_name }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  deploy:
    if: "github.repository_owner == 'kcp-dev' && github.ref_name == 'main'"
    name: Deploy KCP
    needs: build
    environment: unstable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the short sha
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -b -7)"

      - name: Set up kubectl and kustomize
        run: |-
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.2/kustomize_v4.5.2_linux_amd64.tar.gz" | tar xzf -
          curl -sLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod u+x ./kubectl
          chmod u+x ./kustomize

      - name: Get the external hostname
        id: external_hostname
        run: echo "::set-output name=external_hostname::$(./kubectl --server=https://${{ secrets.CICD_KUBE_HOST }} --token=${{ secrets.CICD_KUBE_TOKEN }} -n ${{ secrets.CICD_KUBE_NS }} get route kcp -o jsonpath='{.spec.host}')"

      - name: Deploy new image to CI
        id: deploy-to-ci
        run: |-
          cd manifest
          ../kustomize edit add patch --patch='[{"op": "replace", "path": "/spec/template/spec/containers/0/env", "value": [{"name": "EXTERNAL_HOSTNAME", "value": "${{ steps.external_hostname.outputs.external_hostname }}"}]}]' --group apps --kind Deployment --name kcp --version v1
          ../kustomize edit add patch --patch='[{"op": "replace", "path": "/spec/host", "value": "${{ steps.external_hostname.outputs.external_hostname }}"}]' --group route.openshift.io --kind Route --name kcp-front-proxy --version v1
          ../kustomize edit add patch --patch='[{"op": "replace", "path": "/spec/dnsNames/0", "value": "${{ steps.external_hostname.outputs.external_hostname }}"}]' --group cert-manager.io --kind Certificate --name kcp-front-proxy --version v1
          ../kustomize edit set image ghcr.io/kcp-dev/kcp=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
          ../kustomize build . | ../kubectl --server=https://${{ secrets.CICD_KUBE_HOST }} --token=${{ secrets.CICD_KUBE_TOKEN }} -n ${{ secrets.CICD_KUBE_NS }} apply -f -
